---
    - name: To cancel the Process for Database Backup
      dsmadmc:
        command: " cancel process {{ item }} "
        se: "{{ lookup('env', 'tsm_server_node') }}"
        id: "{{ lookup('env', 'tsm_app_user') }}"
        pa: "{{ lookup('env', 'tsm_app_password') }}"
      loop: "{{ proc_num }}"