---
    - name: To cancel the Process for Database Backup
      dsmadmc:
        command: " cancel process {{ item }} "
        se: "{{ tsm_server_node }}"
        id: "{{ tsm_app_user }}"
        pa: "{{ tsm_app_password }}"
      loop: "{{ proc_num }}"